blueprint:
  name: IKEA MYGGBETT (Door/Window) – Open/Close Actions + Left Open Reminder (Fixed)
  description: >
    Run actions when a door/window contact sensor opens or closes, with optional open delay
    and an optional reminder if it stays open.
    Works with IKEA MYGGBETT and any binary_sensor contact.
  domain: automation
  input:
    contact_sensor:
      name: Door/Window Sensor
      selector:
        entity:
          domain: binary_sensor

    open_delay:
      name: Open delay (seconds)
      description: Sensor must remain open for this many seconds before "open" actions run.
      default: 0
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: seconds
          mode: slider

    open_actions:
      name: Actions when opened
      default: []
      selector:
        action: {}

    close_actions:
      name: Actions when closed
      default: []
      selector:
        action: {}

    left_open_enabled:
      name: Enable "left open" reminder
      default: false
      selector:
        boolean: {}

    left_open_for:
      name: Reminder if left open for (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          step: 1
          unit_of_measurement: minutes
          mode: slider

    left_open_actions:
      name: Reminder actions
      default: []
      selector:
        action: {}

mode: restart

trigger:
  # Opened (optionally delayed by "for")
  - platform: state
    entity_id: !input contact_sensor
    to: "on"
    for:
      seconds: !input open_delay
    id: opened

  # Closed
  - platform: state
    entity_id: !input contact_sensor
    to: "off"
    id: closed

  # Left open reminder trigger (fires only if it stays open)
  - platform: state
    entity_id: !input contact_sensor
    to: "on"
    for:
      minutes: !input left_open_for
    id: left_open

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: opened
        sequence: !input open_actions

      - conditions:
          - condition: trigger
            id: closed
        sequence: !input close_actions

      - conditions:
          - condition: trigger
            id: left_open
          - condition: template
            value_template: "{{ is_state('input_boolean.dummy', 'on') }}"
        sequence: !input left_open_actions
